# Midterm 1: run the data generator in Colab

Use this notebook if you cannot run Python or git on your own machine. It only **generates and shows your data**. You write your answers in `ANSWERS.md` on **your fork on github.com** (open the file, click the pencil icon, edit, *Commit changes*), then submit the commit URL in Canvas. See the README for the rules.

1. Fill in `GITHUB_USERNAME` (the account that owns your fork) and `CODE` (`PRACTICE` to rehearse; the real code is on the board during the exam).
2. Run the three code cells in order.

In [20]:
GITHUB_USERNAME = "NikitaStrongest1"
CODE = "zebra-28"
assert GITHUB_USERNAME, "fill in GITHUB_USERNAME first"

In [21]:
import os

if not os.path.exists("midterm-1-AI-course"):
    !git clone --quiet https://github.com/unreal-kz/midterm-1-AI-course.git
%cd midterm-1-AI-course
!python make_my_data.py --github {GITHUB_USERNAME} --code {CODE}

/content/midterm-1-AI-course/midterm-1-AI-course/midterm-1-AI-course/midterm-1-AI-course/midterm-1-AI-course
Wrote 3 files to my_data/ · fingerprint 65cf1eaa
Next: open my_data/DATA.md

In [22]:
import pandas as pd
from IPython.display import Markdown, display

display(Markdown(open("my_data/DATA.md", encoding="utf-8").read()))
ranks = pd.read_csv("my_data/retrieval_ranks.csv")   # Part 1
docs = pd.read_csv("my_data/doc_results.csv")        # Part 2
display(ranks.head(), docs)

# Midterm 1: your data

GitHub username: `nikitastrongest1` · session code: `zebra-28` · generator v1

**Fingerprint: `65cf1eaa`**: copy it into the first lines of `ANSWERS.md`. All numbers below are synthetic: this is an exam, not a measurement.

## Part 1: inputs

`retrieval_ranks.csv`: 60 test questions (20 EN, 20 RU, 20 KK). `rank_A` and `rank_B` give the position of the correct chunk in the top 10 retrieved under config A and config B; **11 means the correct chunk was not in the top 10.**

Production traffic and Model M token counts (tokens per item, as counted by Model M's tokenizer):

| language | share of traffic | question tokens | answer tokens | chunk A tokens | chunk B tokens |
|---|---|---|---|---|---|
| EN | 44 % | 28 | 131 | 274 | 76 |
| RU | 41 % | 51 | 237 | 496 | 138 |
| KK | 15 % | 54 | 253 | 529 | 147 |

- Requests per day: **11,000**, in the traffic shares above.
- System prompt: **195** tokens in every request.
- Price: **$1** per million input tokens, **$6** per million output tokens.
- Annual budget for this service (model calls only): **$9,100**.

## Part 2: inputs

`doc_results.csv`: for each pipeline, language and scan condition, `n_docs` test invoices and `n_correct` = invoices whose number, date, seller ID and total were all extracted exactly (strict scorer, as in Lab 04).

- **Pipeline H**: hosted vision-language API in a data centre abroad, pay per token; each page is sent as an image.
- **Pipeline L**: open vision-language model on your own server in Kazakhstan, fixed monthly cost.

- Volume: **3,000** scanned pages per day. In **22 %** of them an individual's name and ИИН are printed (sole proprietors, receipts).
- Page image: **1654 × 2339** pixels. Pipeline H counts an image as ⌈width ÷ 28⌉ × ⌈height ÷ 28⌉ input tokens and returns about **294** output tokens per page (the JSON).
- Pipeline H price: **$3** per million input tokens, **$15** per million output tokens.
- Pipeline L: one server costs **$900** per month and handles up to **8,000** pages per day; add servers as needed.

## Part 3: your five questions

Answer each in `ANSWERS.md`: one **Number** line and one **Why** line of at most 40 words.

### Q1

The same support request, once in English and once in Kazakh, through Model M ($2 per million input tokens, $12 per million output tokens):

| | input tokens | output tokens |
|---|---|---|
| EN | 1,451 | 123 |
| KK | 4,335 | 183 |

Compute the token ratio (total tokens KK ÷ EN) and the bill ratio (cost KK ÷ cost EN). **Number:** the bill ratio (2 decimals). **Why** (at most 40 words): why is the bill ratio not equal to the token ratio?

### Q2

A teammate sets the chunk size to **640 tokens, counted with cl100k**. The retrieval model (e5-small) reads at most 512 of *its own* tokens. Assume e5 tokens grow in proportion to cl100k tokens at the rate measured in Lecture 4.1 (a chunker told 256 cl100k tokens produced chunks of 263 / 128 / 76 e5 tokens for EN / RU / KK), and that every chunk is exactly the full size.

In an English chunk, the sentence that contains the answer starts 70 % of the way into the chunk and is shorter than 20 e5 tokens. **Number:** the position of the start of that sentence, in e5 tokens (nearest integer). **Why** (at most 40 words): can a question that matches only that sentence retrieve this chunk, and would you see an error?

### Q3

A language model gives these next-token scores for the prompt "The branch is closed on":

| token | score |
|---|---|
| Monday | 4.2 |
| Friday | 2.9 |
| Sunday | 1.8 |
| holiday | 1.2 |
| Easter | 0.1 |

Use temperature T = 1, then apply top-p = 0.95. **Number:** the probability of the top token after top-p and renormalisation, in percent (1 decimal). **Why** (at most 40 words): how does top-p differ from lowering the temperature?

### Q4

Two models answer the same 100 factual questions (1 point per correct answer on the public leaderboard):

| | correct | wrong | "I don't know" |
|---|---|---|---|
| Model X | 74 | 26 | 0 |
| Model Y | 72 | 12 | 16 |

Now score them again with a penalty: +1 per correct answer, −1 per wrong answer, 0 for "I don't know". **Number:** Y's penalised score minus X's (negative if X is ahead). **Why** (at most 40 words): which model does the public leaderboard prefer, and what does that teach a model to do?

### Q5

A lab trains a model with **13 billion parameters on 4.862 trillion tokens**. Chinchilla (Lecture 1.1) trained 70 billion parameters on 1.4 trillion tokens, which the paper presents as the compute-optimal ratio. **Number:** this model's tokens per parameter divided by Chinchilla's tokens per parameter (2 decimals). **Why** (at most 40 words): is the model under- or over-trained by that criterion, and what did Chinchilla say about models such as GPT-3?

   qid lang  rank_A  rank_B
0  q01   RU      11      11
1  q02   KK       1       1
2  q03   EN       1       2
3  q04   RU      11      11
4  q05   KK      11      11

   pipeline lang condition  n_docs  n_correct
0         H   EN     clean      30         30
1         H   EN  degraded      30         27
2         H   RU     clean      30         28
3         H   RU  degraded      30         26
4         H   KK     clean      30         27
5         H   KK  degraded      30         26
6         L   EN     clean      30         27
7         L   EN  degraded      30         23
8         L   RU     clean      30         27
9         L   RU  degraded      30         24
10        L   KK     clean      30         25
11        L   KK  degraded      30         17

`ranks` and `docs` are ready for you to compute with. Remember the **fingerprint** at the top of the data sheet: it goes into the first lines of `ANSWERS.md`.

part1

In [23]:
display(ranks)

    qid lang  rank_A  rank_B
0   q01   RU      11      11
1   q02   KK       1       1
2   q03   EN       1       2
3   q04   RU      11      11
4   q05   KK      11      11
5   q06   KK      11       4
6   q07   RU       1       3
7   q08   RU       1       1
8   q09   RU       1       1
9   q10   RU       1       1
10  q11   EN       5       5
11  q12   KK       2       5
12  q13   RU       1       3
13  q14   KK       2       3
14  q15   KK       5       9
15  q16   KK       1       1
16  q17   RU      11      11
17  q18   KK       1       2
18  q19   EN      11       4
19  q20   KK       1       3
20  q21   EN       2       2
21  q22   EN       1       1
22  q23   EN       5       4
23  q24   KK       1       1
24  q25   RU      11      11
25  q26   KK       1       5
26  q27   RU      11       7
27  q28   EN       1       1
28  q29   KK       1       2
29  q30   EN       1       1
30  q31   RU      11       4
31  q32   KK       1       1
32  q33   EN      11       4
33  q34   EN       3       5
34  q35   EN       1       2
35  q36   EN       4       5
36  q37   RU       1       1
37  q38   KK       2       2
38  q39   RU       1       1
39  q40   EN       2       4
40  q41   KK       1       3
41  q42   RU       3       3
42  q43   EN       1       3
43  q44   EN       2       2
44  q45   KK       1       1
45  q46   EN       1       1
46  q47   KK      11      11
47  q48   EN       1       1
48  q49   RU       3       2
49  q50   RU      11       5
50  q51   RU       1       1
51  q52   KK       1       1
52  q53   KK       1       4
53  q54   EN       1       1
54  q55   KK       1       1
55  q56   RU       5       5
56  q57   RU      11      11
57  q58   RU       1       1
58  q59   EN      11      11
59  q60   EN       1       1

In [24]:
import numpy as np

n = len(ranks)

for config in ["A", "B"]:
    rank = ranks[f"rank_{config}"]

    recall_1 = (rank <= 1).mean()
    recall_3 = (rank <= 3).mean()
    recall_5 = (rank <= 5).mean()

    reciprocal_rank = np.where(rank <= 10, 1 / rank, 0)
    mrr_10 = reciprocal_rank.mean()

    print(f"Config {config}")
    print(f"Recall@1: {recall_1:.4f}")
    print(f"Recall@3: {recall_3:.4f}")
    print(f"Recall@5: {recall_5:.4f}")
    print(f"MRR@10:   {mrr_10:.4f}")
    print()

Config A
Recall@1: 0.5333
Recall@3: 0.6833
Recall@5: 0.7667
MRR@10:   0.6175

Config B
Recall@1: 0.3500
Recall@3: 0.6000
Recall@5: 0.8333
MRR@10:   0.5123

In [25]:
from statsmodels.stats.proportion import proportion_confint

n = 60
candidates = [
    ("A, k=3", 41),
    ("A, k=5", 46),
    ("B, k=3", 36),
    ("B, k=5", 50)]
for name, x in candidates:
    recall = x / n
    lower, upper = proportion_confint(x, n, alpha=0.05, method="wilson")
    print(name)
    print("Recall:", round(recall, 4))
    print("Lower:", round(lower, 4))
    print("Upper:", round(upper, 4))
    print()

A, k=3
Recall: 0.6833
Lower: 0.5577
Upper: 0.7869

A, k=5
Recall: 0.7667
Lower: 0.6456
Upper: 0.8556

B, k=3
Recall: 0.6
Lower: 0.4737
Upper: 0.7143

B, k=5
Recall: 0.8333
Lower: 0.7197
Upper: 0.9069

In [26]:

# Part 1c: Annual model cost in USD

requests_per_day = 7500
days_per_year = 365
system_prompt_tokens = 245
input_price = 3
output_price = 18


data = {
    "EN": {
        "share": 0.35,
        "question": 40,
        "answer": 90,
        "chunk_A": 268,
        "chunk_B": 69
    },
    "RU": {
        "share": 0.27,
        "question": 57,
        "answer": 129,
        "chunk_A": 383,
        "chunk_B": 99
    },
    "KK": {
        "share": 0.38,
        "question": 141,
        "answer": 318,
        "chunk_A": 946,
        "chunk_B": 244
    }
}

def annual_cost(config, k):
    daily_input_tokens = 0
    daily_output_tokens = 0

    for lang, values in data.items():
        requests = requests_per_day * values["share"]
        chunk_tokens = values[f"chunk_{config}"]

        input_per_request = (
            system_prompt_tokens
            + values["question"]
            + k * chunk_tokens
        )

        output_per_request = values["answer"]

        daily_input_tokens += requests * input_per_request
        daily_output_tokens += requests * output_per_request


    annual_input_tokens = daily_input_tokens * days_per_year
    annual_output_tokens = daily_output_tokens * days_per_year

    cost = (
        annual_input_tokens * input_price
        + annual_output_tokens * output_price
    ) / 1_000_000

    return cost


results = {
    "A, k=3": annual_cost("A", 3),
    "A, k=5": annual_cost("A", 5),
    "B, k=3": annual_cost("B", 3),
    "B, k=5": annual_cost("B", 5)
}


for candidate, cost in results.items():
    print(f"{candidate}: ${cost:,.2f}")

A, k=3: $25,631.71
A, k=5: $34,775.34
B, k=3: $15,454.20
B, k=5: $17,812.83

In [29]:
import pandas as pd

# Load your generated data
df = pd.read_csv(
    "/content/midterm-1-AI-course/my_data/retrieval_ranks.csv"
)

# Calculate Recall@5 for each language for Candidate B
recall_by_language = (
    df.assign(relevant=df["rank_B"] <= 5)
      .groupby("lang")["relevant"]
      .mean()
)

print("Candidate B, k = 5: Recall by language")
for lang in ["EN", "RU", "KK"]:
    print(f"{lang}: {recall_by_language[lang]:.4f} "
          f"({recall_by_language[lang] * 100:.2f}%)")

Candidate B, k = 5: Recall by language
EN: 0.7500 (75.00%)
RU: 0.7000 (70.00%)
KK: 0.7000 (70.00%)